spring:
  application:
    name: train
  datasource:
    url: jdbc:oracle:thin:@10.10.0.202:1521:orcl
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.OracleDialect
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        generate_statistics: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      transaction-id-prefix: my-tx-prefix-
    consumer:
      group-id: log-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      isolation-level: read_committed
    listener:
      ack-mode: manual_immediate

logging:
  level:
    org:
      springframework:
        security: OFF

rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}

jwt:
  access-token-alive-time: 3600 #seconds
  refresh-token-alive-time: 604800 #seconds