spring:
  application:
    name: train
  datasource:
    url: jdbc:oracle:thin:@10.10.0.202:1521:orcl
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE

rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}

jwt:
  alive-time: 600 #seconds